export default {
  products: [
    {
      _id: "1",
      name: "Slim T-Shirt",
      category: "T-Shirt",
      image: "/images/pic1.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "2",
      name: "Fit T-Shirt",
      category: "T-Shirt",
      image: "/images/pic2.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "3",
      name: "Slim T-Shirt",
      category: "T-Shirt",
      image: "/images/pic3.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "4",
      name: "Fit T-Shirt",
      category: "T-Shirt",
      image: "/images/pic4.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "5",
      name: "T-Shirt Long Sheeve",
      category: "T-Shirt",
      image: "/images/pic1.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "6",
      name: "Slim T-Shirt",
      category: "T-Shirt",
      image: "/images/pic4.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "7",
      name: "Fit T-Shirt",
      category: "T-Shirt",
      image: "/images/pic2.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "8",
      name: "Slim T-Shirt",
      category: "T-Shirt",
      image: "/images/pic3.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "9",
      name: "Fit T-Shirt",
      category: "T-Shirt",
      image: "/images/pic4.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
    {
      _id: "10",
      name: "T-Shirt Long Sheeve",
      category: "T-Shirt",
      image: "/images/pic1.jpg",
      price: 10,
      brand: "Camstòr",
      rating: 4.5,
      numReviews: 20,
    },
  ],
};
